version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=${OIDC_RSA_KEY_1}
    env_file:
      - .env
